name: check-integration-test
on: [push, pull_request]
jobs:
  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.9.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          command: npm run test:e2e

