name: check-rust
on:
  push:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.95
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
      - name: Build (all features)
        run: cargo build --workspace --all-features
        env:
          RUSTFLAGS: -D warnings
      - name: Test (all features)
        run: cargo test --workspace --all-features
      - name: Test httpd without search
        run: cargo test -p radicle-httpd

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.95
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
      - name: Docs
        run: cargo doc --workspace --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.95
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
      - name: Run clippy
        run: cargo clippy --workspace --all-features --tests
        env:
          RUSTFLAGS: -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
