name: check-unit-test
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.9.0'
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: ./scripts/unit-test
        shell: bash
