name: check-unit-test
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:unit
